### ISSUE TITLE
Decide a webpage

### ISSUE THREAD

**Issue by XinyuanMO** [zccwqdoorchid/IKEA-meatballs#2]
Let's decide the webpage that we want to extract text from!

**Comment by zccwqdoorchid** [comment]
What do you have in mind? I tried a weather web and a news web, the tags were so long and complex that I couldn't extract properly lol
How about this one? Thought you might be interested https://ilmonet.fi/search?cgt=723,716,968&com=3&status=-10000&page=1&limits=16&list_type=30&sort=2500

**Comment by XinyuanMO** [comment]
Yes this website's interesting indeed! 

The only problem I found is that most of its contents are in Finnish (even after switching the language into English), therefore it might be a little hard to check if the info we retrieve are the right content we want (but I think it would be fine if we only retrieve all the time and availability info for ceramic courses in the first 3 months of 2024, for example, since these are in English). 

What do you think? Should we go for things like time/seat info on **this** website or change to another fully-in-English one with similar content? (I'm happy with both!)

**Comment by zccwqdoorchid** [comment]
Yes, the language is indeed a problem, maybe we should switch to an English website considering it's our (at least my) first time doing this, we shouldn't further complicate things lol. 

What English website do you have in mind? I'm fine with anything.

**Comment by XinyuanMO** [comment]
I just got this random baking website https://sallysbakingaddiction.com/
with an updating list of new recipes. Is this an okay option? :)

**Comment by zccwqdoorchid** [comment]
Looks nice, let's do this one then. Do you have specific set of recipes (cakes, bread, etc.) in mind or are we doing the front page?

**Comment by XinyuanMO** [comment]
Let's go with pies! Here's its Pies, Crisps, & Tarts webpage: https://sallysbakingaddiction.com/category/desserts/pies-crisps-tarts/

**Comment by zccwqdoorchid** [comment]
So I was blocked by the website when I was trying to use soup.get_text(), this was after my numerous attempts of extracting tags, so I'm not sure what to do now. I wasn't able to return keywords or tags at all from this website (I kept getting []). Any luck for you?

**Comment by XinyuanMO** [comment]
switched to another website: https://www.bbcgoodfood.com/recipes/collection/pie-recipes
problem solved!
